<?php

namespace AppBundle\Repository;

/**
 * LocatieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocatieRepository extends \Doctrine\ORM\EntityRepository
{
}
