<?php

namespace AppBundle\Repository;

/**
 * VoorraadbeheerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoorraadbeheerRepository extends \Doctrine\ORM\EntityRepository
{
}
